# Generated by Django 4.1 on 2024-01-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
